server:
  port: 8082
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost8081/eureka
      
spring:
  cloud:
    config:
      server:
        git:
          uri:  https://github.com/zhao-db/config-server
          search-paths: config*
          username: zhao-db@neusoft.com
          password: zhaodongbao01
          
  application:
    name: config-server